<?php

declare(strict_types=1);

namespace LaravelHyperf\Support\Facades;

use LaravelHyperf\Scheduling\Schedule as ScheduleAccessor;

/**
 * @method static \LaravelHyperf\Scheduling\CallbackEvent call(string|callable $callback, array $parameters = [])
 * @method static \LaravelHyperf\Scheduling\Event command(string $command, array $parameters = [])
 * @method static \LaravelHyperf\Scheduling\CallbackEvent job(object|string $job, string|null $queue = null, string|null $connection = null)
 * @method static \LaravelHyperf\Scheduling\Event exec(string $command, array $parameters = [])
 * @method static void group(\Closure $events)
 * @method static string compileArrayInput(string|int $key, array $value)
 * @method static bool serverShouldRun(\LaravelHyperf\Scheduling\Event $event, \DateTimeInterface $time)
 * @method static \Hyperf\Collection\Collection dueEvents(\LaravelHyperf\Contracts\Foundation\Application $app)
 * @method static \LaravelHyperf\Scheduling\Event[] events()
 * @method static \LaravelHyperf\Scheduling\Schedule useCache(string $store)
 * @method static void macro(string $name, object|callable $macro)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static bool hasMacro(string $name)
 * @method static void flushMacros()
 * @method static mixed macroCall(string $method, array $parameters)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes withoutOverlapping(int $expiresAt = 1440)
 * @method static void mergeAttributes(\LaravelHyperf\Scheduling\Event $event)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes user(string $user)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes environments(array|mixed $environments)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes evenInMaintenanceMode()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes onOneServer()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes runInBackground()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes when(\Closure|bool $callback)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes skip(\Closure|bool $callback)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes name(string $description)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes description(string $description)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes cron(string $expression)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes between(string $startTime, string $endTime)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes unlessBetween(string $startTime, string $endTime)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everySecond()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTwoSeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFiveSeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTenSeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFifteenSeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTwentySeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyThirtySeconds()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyMinute()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTwoMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyThreeMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFourMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFiveMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTenMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFifteenMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyThirtyMinutes()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes hourly()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes hourlyAt(array|string|int|int[] $offset)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyOddHour(array|string|int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyTwoHours(array|string|int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyThreeHours(array|string|int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everyFourHours(array|string|int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes everySixHours(array|string|int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes daily()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes at(string $time)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes dailyAt(string $time)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes twiceDaily(int $first = 1, int $second = 13)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes twiceDailyAt(int $first = 1, int $second = 13, int $offset = 0)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes weekdays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes weekends()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes mondays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes tuesdays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes wednesdays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes thursdays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes fridays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes saturdays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes sundays()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes weekly()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes weeklyOn(array|mixed $dayOfWeek, string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes monthly()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes monthlyOn(int $dayOfMonth = 1, string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes twiceMonthly(int $first = 1, int $second = 16, string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes lastDayOfMonth(string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes quarterly()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes quarterlyOn(int $dayOfQuarter = 1, string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes yearly()
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes yearlyOn(int $month = 1, int|string $dayOfMonth = 1, string $time = '0:0')
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes days(array|mixed $days)
 * @method static \LaravelHyperf\Scheduling\PendingEventAttributes timezone(\DateTimeZone|string $timezone)
 *
 * @see \LaravelHyperf\Scheduling\Schedule
 */
class Schedule extends Facade
{
    protected static function getFacadeAccessor()
    {
        return ScheduleAccessor::class;
    }
}
