name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: "8.2"
            swoole: "5.1.6"
          - php: "8.3"
            swoole: "5.1.6"

    name: PHP ${{ matrix.php }} (swoole-${{ matrix.swoole }})

    container:
      image: phpswoole/swoole:${{ matrix.swoole }}-php${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist -n -o
            composer config repositories.facade-documenter vcs git@github.com:laravel-hyperf/facade-documenter.git
            composer require --dev laravel-hyperf/facade-documenter:dev-main

      - name: Lint facades documents
        run: find src/support/src/Facades -type f -name '*.php' -printf '%f\n' | sort | grep -v Facade | sed -E 's/(.+)\.php/LaravelHyperf\\\\Support\\\\Facades\\\\\1/' | xargs php -f vendor/bin/facade.php -- --lint

      - name: Lint coding style
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml.dist
